# Generated by Django 4.2.7 on 2025-10-23 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='criteria_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic scoring criteria as JSON {criterion_id: score}'),
        ),
        migrations.AlterField(
            model_name='score',
            name='artistic_expression',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Artistic Expression score (0-25)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='overall_impression',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Overall Impression score (0-25)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='stage_presence',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Stage Presence score (0-25)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='technical_skill',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Technical Skill score (0-25)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
