# Generated by Django 4.2.7 on 2025-08-17 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_allowedemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedemail',
            options={'verbose_name': 'Allowed Email', 'verbose_name_plural': 'Allowed Emails'},
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
