# Generated by Django 4.2.7 on 2025-09-12 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_allowedemail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('LP', 'Lower Primary'), ('UP', 'Upper Primary'), ('HS', 'High School'), ('HSS', 'Higher Secondary School')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='allowedemail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Allowed Email', 'verbose_name_plural': 'Allowed Emails'},
        ),
        migrations.AddField(
            model_name='user',
            name='college_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='college_id_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_category_extra',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowedemail_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.school'),
        ),
    ]
