# Generated by Django 4.2.7 on 2025-09-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_school_alter_allowedemail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_id_photos/'),
        ),
    ]
