# Generated by Django 4.2.7 on 2025-09-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_approval_status_user_staff_id_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='judge_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='judge_id_photos/'),
        ),
    ]
