# Generated by Django 4.2.7 on 2025-10-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_judge_id_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_password_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
