# Generated by Django 4.2.7 on 2025-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_pending_password_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
