# Generated by Django 4.2.7 on 2025-10-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_must_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
