# Generated by Django 4.2.7 on 2025-10-22 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_generate_chess_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='assigned_volunteer_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
